// youtube video
export const SET_CURRENT_VIDEOID = "SET_CURRENT_VIDEOID"
export const SET_SELECTEDPLKEY = "SET_SELECTEDPLKEY"
export const SET_SELECTEDMLKEY = "SET_SELECTEDMLKEY"
export const SET_SELECTED_KEY = "SET_SELECTED_KEY"
export const SET_PREV_PLKEY = "SET_PREV_PLKEY"

// chat
export const SET_CHAT_MESSAGE = "SET_CHAT_MESSAGE"
export const ADD_CHAT_DATA = "ADD_CHAT_DATA"